version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: crowd-shipping-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crowdshipping
      POSTGRES_PASSWORD: crowdshipping
      POSTGRES_DB: crowdshipping
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: